const BOX_STATUS = {
  PENDING_OUTBOUND: 'PENDING_OUTBOUND',
  IN_TRANSIT: 'IN_TRANSIT',
  PENDING_SIGN: 'PENDING_SIGN',
  SIGNED: 'SIGNED',
  FROZEN: 'FROZEN',
  REVIEWED_CLOSED: 'REVIEWED_CLOSED'
};

const BOX_STATUS_LABELS = {
  [BOX_STATUS.PENDING_OUTBOUND]: '待出库',
  [BOX_STATUS.IN_TRANSIT]: '运输中',
  [BOX_STATUS.PENDING_SIGN]: '待签收',
  [BOX_STATUS.SIGNED]: '已签收',
  [BOX_STATUS.FROZEN]: '异常冻结',
  [BOX_STATUS.REVIEWED_CLOSED]: '复核关闭'
};

const CHECK_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  CONFIRMED: 'CONFIRMED'
};

const CHECK_STATUS_LABELS = {
  [CHECK_STATUS.DRAFT]: '草稿',
  [CHECK_STATUS.SUBMITTED]: '已提交',
  [CHECK_STATUS.CONFIRMED]: '已确认'
};

const DIFF_TYPE = {
  EXTRA_SCAN: 'EXTRA_SCAN',
  MISSING_SCAN: 'MISSING_SCAN',
  STATUS_MISMATCH: 'STATUS_MISMATCH',
  LOCATION_MISMATCH: 'LOCATION_MISMATCH'
};

const DIFF_TYPE_LABELS = {
  [DIFF_TYPE.EXTRA_SCAN]: '多扫',
  [DIFF_TYPE.MISSING_SCAN]: '漏扫',
  [DIFF_TYPE.STATUS_MISMATCH]: '状态不匹配',
  [DIFF_TYPE.LOCATION_MISMATCH]: '库位不一致'
};

const AUDIT_ACTION = {
  IMPORT: 'IMPORT',
  OUTBOUND: 'OUTBOUND',
  SIGN: 'SIGN',
  FREEZE: 'FREEZE',
  REVIEW_CLOSE: 'REVIEW_CLOSE',
  CHECK_CREATE: 'INVENTORY_CHECK_CREATE',
  CHECK_ADD_ITEMS: 'INVENTORY_CHECK_ADD_ITEMS',
  CHECK_SUBMIT: 'INVENTORY_CHECK_SUBMIT',
  CHECK_CONFIRM: 'INVENTORY_CHECK_CONFIRM'
};

const ERROR_HTTP_STATUS = {
  MISSING_OPERATOR: 401,
  INVALID_ROLE: 401,
  PERMISSION_DENIED: 403,
  DUPLICATE_BATCH: 400,
  DUPLICATE_BOX: 400,
  DUPLICATE_SIGN: 400,
  INVALID_TEMPERATURE: 400,
  INVALID_SEAL: 400,
  TIMEOUT: 400,
  BATCH_NOT_FOUND: 404,
  BOX_NOT_FOUND: 404,
  INVALID_STATUS_TRANSITION: 400,
  ALREADY_FROZEN: 400,
  ALREADY_CLOSED: 400,
  NOT_FROZEN: 400,
  INVALID_PARAMS: 400,
  INVALID_TYPE: 400,
  EMPTY_BOXES: 400,
  MISSING_BOX_NO: 400,
  INVALID_STATUS: 400,
  MISSING_REASON: 400,
  CONFIG_NOT_FOUND: 404,
  DUPLICATE_CHECK_NO: 400,
  CHECK_NOT_FOUND: 404,
  CHECK_NOT_DRAFT: 400,
  CHECK_ALREADY_SUBMITTED: 409,
  CHECK_ALREADY_CONFIRMED: 409,
  CHECK_NOT_SUBMITTED: 400,
  INVALID_CHECK_STATUS: 400,
  DUPLICATE_BOX_IN_CHECK: 400,
  DUPLICATE_BOX_IN_REQUEST: 400,
  BOX_CLOSED: 400,
  BOX_FROZEN: 400,
  EMPTY_CHECK_ITEMS: 400
};

function httpStatusFor(errorCode) {
  return ERROR_HTTP_STATUS[errorCode] || 400;
}

module.exports = {
  BOX_STATUS,
  BOX_STATUS_LABELS,
  CHECK_STATUS,
  CHECK_STATUS_LABELS,
  DIFF_TYPE,
  DIFF_TYPE_LABELS,
  AUDIT_ACTION,
  ERROR_HTTP_STATUS,
  httpStatusFor
};
